/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.peluqueriagui;

/**
 *
 * @author alumno
 */
public class Datos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Datos.class.getName());

    /**
     * Creates new form Datos
     */
    public Datos() {
        initComponents();
        setExtendedState(getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
        String inicial = (String) boxTablas.getSelectedItem(); 
        ((java.awt.CardLayout) panelTablas.getLayout()).show(panelTablas, inicial);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPestanas = new javax.swing.JTabbedPane();
        panelDatos = new javax.swing.JPanel();
        boxTablas = new javax.swing.JComboBox<>();
        panelTablas = new javax.swing.JPanel();
        panelClientes = new javax.swing.JPanel();
        panelPeluqueras = new javax.swing.JPanel();
        panelServicios = new javax.swing.JPanel();
        panelProductos = new javax.swing.JPanel();
        panelConsultas = new javax.swing.JPanel();
        panelVis = new javax.swing.JPanel();
        panelSincro = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        boxTablas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clientes", "Peluqueras", "Servicios", "Productos" }));
        boxTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTablasActionPerformed(evt);
            }
        });

        panelTablas.setLayout(new java.awt.CardLayout());

        panelClientes.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        panelTablas.add(panelClientes, "Clientes");

        panelPeluqueras.setBackground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout panelPeluquerasLayout = new javax.swing.GroupLayout(panelPeluqueras);
        panelPeluqueras.setLayout(panelPeluquerasLayout);
        panelPeluquerasLayout.setHorizontalGroup(
            panelPeluquerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );
        panelPeluquerasLayout.setVerticalGroup(
            panelPeluquerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        panelTablas.add(panelPeluqueras, "Peluqueras");

        panelServicios.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout panelServiciosLayout = new javax.swing.GroupLayout(panelServicios);
        panelServicios.setLayout(panelServiciosLayout);
        panelServiciosLayout.setHorizontalGroup(
            panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );
        panelServiciosLayout.setVerticalGroup(
            panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        panelTablas.add(panelServicios, "Servicios");

        panelProductos.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        panelTablas.add(panelProductos, "Productos");

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTablas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(boxTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boxTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTablas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelPestanas.addTab("Datos", panelDatos);

        javax.swing.GroupLayout panelConsultasLayout = new javax.swing.GroupLayout(panelConsultas);
        panelConsultas.setLayout(panelConsultasLayout);
        panelConsultasLayout.setHorizontalGroup(
            panelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        panelConsultasLayout.setVerticalGroup(
            panelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        panelPestanas.addTab("Consultas", panelConsultas);

        javax.swing.GroupLayout panelVisLayout = new javax.swing.GroupLayout(panelVis);
        panelVis.setLayout(panelVisLayout);
        panelVisLayout.setHorizontalGroup(
            panelVisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        panelVisLayout.setVerticalGroup(
            panelVisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        panelPestanas.addTab("Visualización", panelVis);

        javax.swing.GroupLayout panelSincroLayout = new javax.swing.GroupLayout(panelSincro);
        panelSincro.setLayout(panelSincroLayout);
        panelSincroLayout.setHorizontalGroup(
            panelSincroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        panelSincroLayout.setVerticalGroup(
            panelSincroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        panelPestanas.addTab("Sincronización", panelSincro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPestanas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPestanas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTablasActionPerformed
        // TODO add your handling code here:
        String key = (String) boxTablas.getSelectedItem();               
        java.awt.CardLayout cl = (java.awt.CardLayout) panelTablas.getLayout();
        cl.show(panelTablas, key);  
    }//GEN-LAST:event_boxTablasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Datos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxTablas;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelConsultas;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelPeluqueras;
    private javax.swing.JTabbedPane panelPestanas;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel panelServicios;
    private javax.swing.JPanel panelSincro;
    private javax.swing.JPanel panelTablas;
    private javax.swing.JPanel panelVis;
    // End of variables declaration//GEN-END:variables
}
